import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd

"""
Test: Login
    Generated by: Lucky Srivastava (ls2170184@gmail.com)
    Generated on 08/01/2022, 16:40:50
"""


def driver():
    global driver 
    driver = webdriver.Chrome("C:/Users/ls217/OneDrive/Desktop/OrangeHRM Automation Scripts/Python Script/Driver/chromedriver.exe")
    
    """step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before,
                                 screenshot_condition=TakeScreenshotConditionType.Success)
    with DriverStepSettings(driver, step_settings):
        """
        
    """yield driverz  
    driver.quit()"""

def Test_Data(getCSV):
    if (getCSV == "OrangeHRM-TestCases - Login-TestData (1).csv"):
        df = pd.read_csv('OrangeHRM-TestCases - Login-TestData (1).csv')
        return df
    else:
        return None
    
 

def test_Login():
    driver()
    print(Test_Data('OrangeHRM-TestCases - Login-TestData (1).csv'))
    
    """Automate_Login_Page_test_cases."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://opensource-demo.orangehrmlive.com/"
    Username = "Admin"
    Password = "admin13"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(ApplicationURL)
    
    
    # 2. Click 'txtUsername'
    txtusername = driver.find_element(By.CSS_SELECTOR, "#txtUsername")
    txtusername.click()

    # 3. Type '{Username}' in 'txtUsername'
    txtusername = driver.find_element(By.CSS_SELECTOR, "#txtUsername")
    txtusername.send_keys(Username)

    # 4. Click 'txtPassword'
    txtpassword = driver.find_element(By.XPATH, "/html/body/div[1]/div/div[3]/div[2]/div[2]/form/div[3]/input")
    txtpassword.click()

    # 5. Type '{Password}' in 'txtPassword'
    txtpassword = driver.find_element(By.XPATH, "/html/body/div[1]/div/div[3]/div[2]/div[2]/form/div[3]/input")
    txtpassword.send_keys(Password)

    # 6. Click 'Submit'
    submit = driver.find_element(By.CSS_SELECTOR, "#btnLogin")
    submit.click()

    # 7. Get text from 'Alert message' if it's visible
    try:
        alert_message = driver.find_element(By.CSS_SELECTOR, "#spanMessage")
        print(alert_message.text)                                           
    except:
        print("Login Successfull")
    
    # 8. Click 'Welcome rakeshShivamShivam' if it's visible
    welcome_rakeshshivamshivam = driver.find_element(By.XPATH, "/html/body/div[1]/div[1]/a[2]")
    welcome_rakeshshivamshivam.click()
    
    time.sleep(5)
    # 9. Click 'Logout' if it's visible 
    logout = driver.find_element(By.XPATH, "//*[@id='welcome-menu']/ul/li[3]/a")
    logout.click()
    
